### PR TITLE
Kwarg optimization wrapper

### PR DESCRIPTION
**Pull request by roya0045**

### CODE REVIEW

**Comment by pv** [comment]
Please make the title shorter, eg "Optimization of functions with keywords instead of vector arguments"

**Comment by roya0045** [comment]
Did you mean the title of this request or the first # tag(title) in the ipynb file?

**Comment by pv** [comment]
In the ipynb file

**Comment by pv** [comment]
Please also add (on a separate line after the title)
`TAGS: Optimization and fitting` 
so it goes to the right place.

**Comment by rgommers** [comment]
Style comment: code is incorrectly indented (mix of tabs/spaces or 4-spaces with 8-spaces), lines are too long, etc. Please run a pep8 checker over it.

**Comment by pv** [comment]
For the purposes of the cookbook, I think only the title and tagging are required changes.

**Comment by roya0045** [comment]
I changed the title, added the tags and used autopep8 and code_prettify on the code ( in the hopes that it changed the white spaces.)

If there is any more improvements feel free to tell me, I'm obviously quite new to this, I don't want to develop bad coding habits.

**Comment by pv** [comment]
Thanks, merged now that the title and tags look ok.

**Comment by roya0045** [comment]
Thanks for the merge!

**Pull request merged**
